[Main]
Title=Accessibility Magnify
Type=XPEPlugin
Description=Ease of Access, Magnify, OnScreenKeybord in addition to narrator
Author=ChriSR
Date=2019.03.16
Version=001
Selected=False
Mandatory=None
NoWarning=False
Level=5
Download_Level=0
Credits=pc
Contact=

[Process]
Echo,"Processing %ScriptTitle%..."
Run,%ScriptFile%,AddFiles

[AddFiles]
If,ExistFile,%ScriptDir%\Accessibility_AddFiles.txt,ExtractListFiles,%ScriptDir%\Accessibility_AddFiles.txt
// add need to check for wim file

